"""add social columns to user

Revision ID: 3179a9aeb968
Revises: 75ae775f174f
Create Date: 2026-01-05 10:03:42.660514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3179a9aeb968'
down_revision = '75ae775f174f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Do not attempt to create a foreign key constraint on SQLite via batch_alter_table
    # because SQLite has limited ALTER TABLE support. The parent_id column exists
    # (created in a prior migration) and will function logically without an enforced FK.
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('github', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('twitter', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('twitter')
        batch_op.drop_column('github')
        batch_op.drop_column('website')

    # ### end Alembic commands ###
