"""add bio and parent_id

Revision ID: 75ae775f174f
Revises: 
Create Date: 2026-01-05 09:56:27.860023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75ae775f174f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add parent_id column to comment table (without adding a foreign-key constraint
    # because SQLite's ALTER TABLE has limited support for adding FKs).
    op.add_column('comment', sa.Column('parent_id', sa.Integer(), nullable=True))

    # Add bio column to user table
    op.add_column('user', sa.Column('bio', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove bio column from user table
    op.drop_column('user', 'bio')

    # Remove parent_id column from comment table
    op.drop_column('comment', 'parent_id')

    # ### end Alembic commands ###
